#docker-compose.ymlのバージョン
version: '3.8'
#docker volumeの設定
volumes:
  docker-volume:

#services以下に各コンテナの設定を書く
services:
  #Webサーバーのコンテナ
  web:
    #image:の右に書いたイメージをDokcerHub（Docker imageを共有するプラットフォーム）から持ってきます
    image: nginx:1.18
    ports:
      - '8000:80'
    # コンテナ間の依存関係を設定する　PHP→Nginxの順にコンテナを起動するようにしている
    depends_on:
      - app
    # ローカルとDockerコンテナ間のファイル共有を設定する
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
  #アプリケーションのコンテナ
  app:
    #DockerHubのイメージをベースにオリジナルのイメージを作成する
    #Dockerfileというテキストファイルの内容にのっとってイメージを構築
    build: ./docker/php
    volumes:
      - .:/var/www/html
  #データベースのコンテナ
  db:
    image: mysql/mysql-server:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    volumes:
      - docker-volume:/var/lib/mysql
